version: '3.1'
services:
  stats-server:
    build: stat-service/stat-server
    image: stat-service-img
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    entrypoint:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_POSTGRES_USER=owner
      - SPRING_DATASOURCE_POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats
    ports:
      - "6451:5432"
    entrypoint:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm-service
    image: ewm-service-img
    container_name: ewm-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name: stats
    ports:
      - "6451:5432"
    entrypoint:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=explorer
      - POSTGRES_PASSWORD=imgroot
